language: python
sudo: false
jdk:
  - oraclejdk8
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
install:
  - "pip install requests"
  - "pip install unittest2"
  - "pip install py2neo"
  - "pip install pymongo==2.9"
  - "pip install mongo-connector"
  - "pip install mongo-orchestration==0.3.1"
env:
  - PYTHONPATH=.
before_script:
  - wget dist.neo4j.org/neo4j-community-3.0.2-unix.tar.gz
  - tar -xzf neo4j-community-3.0.2-unix.tar.gz
  - echo 'dbms.memory.pagecache.size=1g' >> neo4j-community-3.0.2/conf/neo4j.conf
  - echo 'dbms.security.auth_enabled=false' >> neo4j-community-3.0.2/conf/neo4j.conf
  - echo 'dbms.memory.heap.max_size=1000' >> neo4j-community-3.0.2/conf/neo4j-wrapper.conf
  - echo 'dbms.memory.heap.initial_size=1000' >> neo4j-community-3.0.2/conf/neo4j-wrapper.conf
  - neo4j-community-3.0.2/bin/neo4j start
  - sleep 35
  - mongo-orchestration start
  - sleep 15
script: python -m unittest discover
after_script:
  - mongo-orchestration stop
