language: python
sudo: false
python:
  - "3.2"
  - "3.3"
  - "3.4"
# command to install dependencies
jdk:
  - oraclejdk7
install:
  - "pip3 install mongo-connector"
  - "pip3 install py2neo"
services:
  - mongodb
env:
  - PYTHONPATH=.
before_script:
  # install Neo4j locally:
  - wget dist.neo4j.org/neo4j-community-2.2.0-unix.tar.gz
  - tar -xzf neo4j-community-2.2.0-unix.tar.gz
  - sed -i.bak s/dbms.security.auth_enabled=true/dbms.security.auth_enabled=false/g neo4j-community-2.2.0/conf/neo4j-server.properties
  - neo4j-community-2.2.0/bin/neo4j start
  - sleep 20
  # - echo "replSet=myReplSett" | sudo tee -a /etc/mongodb.conf
  # - sudo service mongodb restart
  # - sleep 20
  - mongo test --eval 'rs.initiate();'
  - sleep 15
# command to run tests
script: python3 -m unittest discover